import React from 'react'
import { NextSeo } from 'next-seo';
import Layout from '../components/layout';
import Head from 'next/head';

import { PHASE_INFO } from '../constants/jsonContent/phaseInfo';
import PhaseLayout from '../components/PhaseLayout';

export default function DesignTheSupportsPage() {
	const phaseInfo = PHASE_INFO.phaseTwo;

	const DesignTheSupports = () => (
		<>
		<PhaseLayout phaseInfo={phaseInfo} />
		</>
	);

	return (
		<>
		<Layout currentPage='design-the-supports'>
			<NextSeo
				title="ESG Social Capital"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<DesignTheSupports />
		</Layout>
		</>
	);
}
