import { setOutgoingHeaders } from '@pantheon-systems/wordpress-kit';
import { NextSeo } from 'next-seo';
import { PostGrid } from '../components/grid';
import Layout from '../components/layout';
import { getFooterMenu } from '../lib/Menus';
import { getLatestPosts } from '../lib/Posts';
import Head from 'next/head';

import styles from './index.module.css';

export default function Home({ menuItems, posts }) {
	const HomepageHeader = () => (
		<div className={`${styles.header} font-extrabold text-center w-fit`}>
			<h1>
				Cultivating Career Connections
			</h1>
		</div>
	);

	return (
		<>
		<Head>
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
			<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet" />
		</Head>

		<Layout footerMenu={menuItems}>
			<NextSeo
				title="ESG Social Capital"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<HomepageHeader />
			<section>
				<PostGrid contentType="posts" data={posts} />
			</section>
		</Layout>
		</>
	);
}

export async function getServerSideProps({ res }) {
	const { menuItems, menuItemHeaders } = await getFooterMenu();
	const { posts, headers: postHeaders } = await getLatestPosts(12);

	const headers = [menuItemHeaders, postHeaders];
	setOutgoingHeaders({ headers, res });

	return {
		props: {
			menuItems,
			posts,
		},
	};
}
