import React from 'react'
import { NextSeo } from 'next-seo';
import Layout from '../components/layout';
import Head from 'next/head';

import { PHASE_INFO } from '../constants/jsonContent/phaseInfo';
import PhaseLayout from '../components/PhaseLayout';


export default function LayTheFoundationPage() {
	const phaseInfo = PHASE_INFO.phaseOne;

	const LayTheFoundation = () => (
		<>
			<PhaseLayout phaseInfo={phaseInfo} />
		</>
	);

	return (
		<>
		<Head>
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
			<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
		</Head>

		<Layout currentPage="lay-the-foundation">
			<NextSeo
				title="ESG Social Capital"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<LayTheFoundation />
		</Layout>
		</>
	);
}

// export async function getServerSideProps({ res }) {
// 	const { menuItems, menuItemHeaders } = await getFooterMenu();
// 	const { posts, headers: postHeaders } = await getLatestPosts(12);

// 	const headers = [menuItemHeaders, postHeaders];
// 	setOutgoingHeaders({ headers, res });

// 	return {
// 		props: {
// 			menuItems,
// 			posts,
// 		},
// 	};
// }
