import React from 'react'
import { NextSeo } from 'next-seo';
import Layout from '../components/layout';
import Head from 'next/head';
import Image from 'next/image';
import HeaderCustom from '../components/HeaderCustom';

import styles from './index.module.css';
import PhaseTitle from '../components/PhaseTitle';
import PhaseContent from "../components/PhaseContent"
import NextPage from "../components/NextPage"

import { PHASE1_CONTENT } from '../constants/jsonContent/phase1content';

import FOLDED_CORNER from "../constants/phase-corner-fold.svg"
import PIN from "../constants/phase1images/phase-pin.svg"
import PHASE1_TITLE_IMG from "../constants/phase1images/p1-title-img.svg"
import Phase1headerContent from '../components/LayTheFoundation/Phase1headerContent';


export default function LayTheFoundationPage() {
	const phaseInfo = {
		headerSvg: PIN,
		phaseNum: 1,
		phaseTitle: "Lay The Foundation",
		phaseHeaderContent: <Phase1headerContent />,
		phaseHeaderImg: PHASE1_TITLE_IMG,
		phaseContent: PHASE1_CONTENT,
		nextPage: "Phase 2: Design The Supports",
		nextPageAnchorLink: "/designthesupports"
	}

	const LayTheFoundation = () => (
		<>
		<div className="layout_folded_corner"><Image src={FOLDED_CORNER} alt="" /></div>
		<HeaderCustom homePageHeader={false}/>
		<div className={`${styles.header} font-extrabold text-center w-fit content-page LayTheFoundation`}>
			<PhaseTitle headerSvg={phaseInfo.headerSvg} phaseNum={phaseInfo.phaseNum} phaseTitle={phaseInfo.phaseTitle} phaseHeaderContent={phaseInfo.phaseHeaderContent} phaseHeaderImg={phaseInfo.phaseHeaderImg}/>
			<PhaseContent phaseContent={phaseInfo.phaseContent}/>	
		</div>
		<NextPage nextPage={phaseInfo.nextPage} nextPageAnchorLink={phaseInfo.nextPageAnchorLink}/>
		</>
	);

	return (
		<>
		<Head>
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
			<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
		</Head>

		<Layout currentPage="lay-the-foundation">
			<NextSeo
				title="ESG Social Capital"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<LayTheFoundation />
		</Layout>
		</>
	);
}

// export async function getServerSideProps({ res }) {
// 	const { menuItems, menuItemHeaders } = await getFooterMenu();
// 	const { posts, headers: postHeaders } = await getLatestPosts(12);

// 	const headers = [menuItemHeaders, postHeaders];
// 	setOutgoingHeaders({ headers, res });

// 	return {
// 		props: {
// 			menuItems,
// 			posts,
// 		},
// 	};
// }
